### ISSUE TITLE
Processing style attribute

### ISSUE THREAD

**Issue by yisibl** [jonathantneal/postcss-write-svg#10]
In svg, we can used style attribute:

``` svg
<path style="stroke-width: 4px; stroke-dasharray: 12px, 6px;" d="M62.9 14.9c-25-7.74-56.6 4.8-60.4 24.3-3.73 19.6 21.6 35 39.6 37.6 42.8 6.2 72.9-53.4 116-58.9 65-18.2 191 101 215 28.8 5-16.7-7-49.1-34-44-34 11.5-31 46.5-14 69.3 9.38 12.6 24.2 20.6 39.8 22.9 91.4 9.05 102-98.9 176-86.7 18.8 3.81 33 17.3 36.7 34.6 2.01 10.2.124 21.1-5.18 30.1" fill="none" stroke="#ffffff"></path>
```

Although we can direct writing:

``` css
@svg path {
  @path {
    stroke-width: 4px; 
    stroke-dasharray: 12px, 6px;
  }
}
```

But also we need a syntax to directly convert style attribute.

cc @tabatkins
