### ISSUE TITLE
Respect var fallbacks

### ISSUE THREAD

**Issue by MadLittleMods** [jonathantneal/postcss-write-svg#17]
Respect custom property variables, `var(value, fallback)`, fallbacks in the second parameter

``` css
@svg square {
    @rect {
        fill: var(--highlight-color, #f00);
        width: 100%;
        height: 100%;
    }
}

.example {
    background: white svg(square) cover;
}
```

Also should work with nested `var` in the fallback.

> Otherwise, if the var() function has a fallback value as its second argument, replace the var() function by the fallback value. If there are any var() references in the fallback, substitute them as well.
> https://drafts.csswg.org/css-variables/#substitute-a-var

``` css
@svg square {
    @rect {
        fill: var(--highlight-color, var(--base-color));
        width: 100%;
        height: 100%;
    }
}

.example {
    background: white svg(square param(--color #00b1ff)) cover;
}
```
