### ISSUE TITLE
invalid css property

### ISSUE THREAD

**Issue by cmnstmntmn** [jonathantneal/postcss-write-svg#18]
the repo box example

``` css
.Leaderboard {
  background: #fff url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IGZpbGw9IiMwMDAiLz48L3N2Zz4=") cover
}
```

<img width="651" alt="screen shot 2016-04-18 at 13 33 12" src="https://cloud.githubusercontent.com/assets/2312755/14601380/7ec238fc-056a-11e6-94ea-8bc41c9438b5.png">
