### ISSUE TITLE
Better syntax and multiplexing

### ISSUE THREAD

**Issue by yisibl** [jonathantneal/postcss-write-svg#4]
We can define a `@svg` name

``` css
@svg 1px-border {
    width: 100%;
    height: 1px;
    rect {
      fill: #c8c7cc;
      x: 0;
      y: 0;
      w: 100%;
      height: 0.5;
    }
}

@svg others {  }
```

Use `svg()`:

``` scss
.bar {
  background-image: svg(1px-border);
}

.baz {
  border-image: svg(1px-border) 2 stretch;
}
```

Output:

``` scss
.bar {
  background-image: url('data:image/svg+xml;charset=utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="1"><rect fill="#c8c7cc" x="0" y="0" width="100%" height="0.5"/></svg>');
}

.baz {
  border-image: url('data:image/svg+xml;charset=utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="1"><rect fill="#c8c7cc" x="0" y="0" width="100%" height="0.5"/></svg>') 2 stretch;
}
```

We can use in different properties. Not only in `background-image`.

This is like Sass `@function`

``` scss

@function svg() {
  @return ...;
}
```
