### ISSUE TITLE
Can configure the output style

### ISSUE THREAD

**Issue by yisibl** [jonathantneal/postcss-write-svg#5]
If there is a quote in the `url()`, this format is better readability.

``` css
.foo {
  background-image: url('data:image/svg+xml;charset=utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="1px"><rect fill="#c8c7cc" x="0" y="0" w="100%" height="0.5"/></svg>')
}
```
